// Hardcoded patient data from CSV for bulk import
import { PatientRecord } from './types';

export const bulkPatientData: Array<Omit<PatientRecord, 'id'>> = [
  {
    patientId: '01-40-48',
    lastName: 'Quilatan',
    firstName: 'Jaiden',
    middleName: 'Beato',
    category: 'MM',
    confinementStart: '2025-07-08',
    confinementEnd: '2025-07-09',
    pin: '190901927387',
    icd10Code: 'R56.0',
    icd10Description: 'Febrile convulsions',
    healthFacilityFee: 9555,
    professionalFee: 4095,
    totalCaseRate: 13650,
    totalBilling: 13650,
    dateFiled: '2025-09-05',
    daysSinceFiled: 0,
    status: 'paid',
    companionName: '',
    relationship: '',
    contactNumber: '',
    homeAddress: '',
    street: '',
    barangay: '',
    city: 'Las Pinas City',
    province: 'Metro Manila',
    zipCode: ''
  },
  {
    patientId: '01-40-29',
    lastName: 'Soriano',
    firstName: 'Lester',
    middleName: 'Cristobal',
    category: 'MM',
    confinementStart: '2025-07-11',
    confinementEnd: '2025-07-13',
    pin: '050259675550',
    icd10Code: 'E29.1',
    icd10Description: 'Testicular hypofunction',
    rvsCode: '54520',
    rvsDescription: 'Orchiectomy',
    healthFacilityFee: 10725,
    professionalFee: 9828,
    totalCaseRate: 20553,
    totalBilling: 20553,
    dateFiled: '2025-09-10',
    daysSinceFiled: 0,
    status: 'paid',
    companionName: '',
    relationship: '',
    contactNumber: '',
    homeAddress: '',
    street: '',
    barangay: '',
    city: 'Las Pinas City',
    province: 'Metro Manila',
    zipCode: ''
  },
  {
    patientId: '01-40-39',
    lastName: 'Dulnuan',
    firstName: 'Kiersten Joy',
    middleName: 'Maugao',
    category: 'MM',
    confinementStart: '2025-07-28',
    confinementEnd: '2025-07-30',
    pin: '010253621198',
    icd10Code: 'A01.0',
    icd10Description: 'Typhoid fever',
    healthFacilityFee: 13650,
    professionalFee: 5850,
    totalCaseRate: 19500,
    totalBilling: 19500,
    dateFiled: '2025-09-11',
    daysSinceFiled: 0,
    status: 'paid',
    companionName: '',
    relationship: '',
    contactNumber: '',
    homeAddress: '',
    street: '',
    barangay: '',
    city: 'Las Pinas City',
    province: 'Metro Manila',
    zipCode: ''
  },
  {
    patientId: '01-40-40',
    lastName: 'Ortilano',
    firstName: 'Ronilo',
    middleName: 'Lapenoso',
    category: 'MM',
    confinementStart: '2025-07-28',
    confinementEnd: '2025-07-31',
    pin: '010270459140',
    icd10Code: 'A01.1',
    icd10Description: 'Paratyphoid fever A',
    healthFacilityFee: 13650,
    professionalFee: 5850,
    totalCaseRate: 19500,
    totalBilling: 19500,
    dateFiled: '2025-09-11',
    daysSinceFiled: 0,
    status: 'paid',
    companionName: '',
    relationship: '',
    contactNumber: '',
    homeAddress: '',
    street: '',
    barangay: '',
    city: 'Las Pinas City',
    province: 'Metro Manila',
    zipCode: ''
  },
  {
    patientId: '01-40-46',
    lastName: 'Ladao',
    firstName: 'Didith',
    middleName: 'Ocampo',
    category: 'MM',
    confinementStart: '2025-08-03',
    confinementEnd: '2025-08-05',
    pin: '012514911620',
    icd10Code: 'I10.1',
    icd10Description: 'Hypertensive heart disease',
    healthFacilityFee: 12285,
    professionalFee: 5265,
    totalCaseRate: 17550,
    totalBilling: 17550,
    dateFiled: '2025-09-17',
    daysSinceFiled: 0,
    status: 'paid',
    companionName: 'Ladao, Raymund David',
    relationship: 'Spouse',
    contactNumber: '0918 910 9477',
    homeAddress: '37 Dona Leoncia Ave. Dona Leoncia Subdivision, Talon 5, LPC',
    street: '37 Dona Leoncia Ave',
    barangay: 'Talon 5',
    city: 'Las Pinas City',
    province: 'Metro Manila',
    zipCode: ''
  }
  // ... I'll add more in a simpler way
];
